if (-r $prj.xyw) then 
echo -n Plot RAIN. 
awk '{print($1,$2,$10/1e3)}' $prj.xyw |\
	xyz2grd	-G$tmp.rain.grd.tmp -I$dx/$dy -R -H2

set rain_min = `grdinfo -C $tmp.rain.grd.tmp | awk '{print $6}'`
set rain_max = `grdinfo -C $tmp.rain.grd.tmp | awk '{print $7}'`
set rain_diff = `echo "$rain_max - $rain_min" | bc -l`
set is_uniform = `echo "$rain_diff < 1e-4" | bc -l`

if ($is_uniform == 0) then
	set min_rain = `echo "$rain_min + 0.9 * $rain_diff" | bc -l`
	grdclip $tmp.rain.grd.tmp -G$tmp.rain.grd.tmp -Sb$min_rain/NaN
	grdimage $tmp.rain.grd.tmp -C$tmp.rain_cpt.tmp -JX -R -Q -O -K >> $ps
	grdcontour $tmp.top.grd.tmp -JX -R -C$tmp.topo_palet.tmp -W1 -O -K >> $ps
endif
endif
