if (-r $prj.st) then
	grdimage $tmp.eros_cumul.grd.tmp -C$tmp.eros_cumul_cpt.tmp -JX -R -Q -O -K >> $ps
	grdcontour $tmp.eros_cumul.grd.tmp -JX -R -C2 -L-14/-2 -W1 -O -K >> $ps
	grdcontour $tmp.eros_cumul.grd.tmp -JX -R -C2 -L2/14 -W1 -O -K >> $ps

pstext	-JX -R -O -K -G0 <<END >> $ps 
	$xtitle	$ytitle	11 0 1 3	erosion (m)
END

psscale -C$tmp.eros_cumul_cpt.tmp -D$xscale/$yscale/$width/$scalewidth\h -B:"Erosion (m)": -L -O -K >> $ps

endif

